---
version: "2"
run:
  # Use the same build tags that are used in magefile.go
  build-tags:
    - exclude_graphdriver_btrfs
linters:
  # https://golangci-lint.run/docs/linters/
  default: standard
  enable:
    - decorder
    - err113
    - gocognit
    - lll
    - makezero
    - modernize
    - paralleltest
    - tparallel
    - prealloc
    - wrapcheck
