version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: capo
    binary: capo
    dir: ./cmd/capo
    ldflags:
      - -extldflags "-static" -s -w -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: ppc64le
    tags:
      - exclude_graphdriver_btrfs
    hooks:
      post:
        - upx -9 "{{ .Path }}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--checksums.txt"

release:
  draft: false

changelog:
  sort: asc
  filters:
    include:
      - "^feat"
      - "^fix"
      - "^chore"
