name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    # TODO: once buildah >= 1.44.0 is available in ubuntu repos, rollback this file to state 
    # of this commit: https://github.com/konflux-ci/capo/commit/80cc28d7b9396021d468e9e42b3d687085ad6ad8
    #- name: Install buildah
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y buildah

    - name: Install mage
      run: go install github.com/magefile/mage@latest

    - name: Download dependencies
      run: mage tidy

    - name: Install buildah build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgpgme-dev libseccomp-dev

    - name: Build custom buildah with intermediate image labeling support
      run: mage BuildCustomBuildah

    - name: Run integration tests with coverage
      run: mage IntegrationCoverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v6
      with:
        use_oidc: true
        flags: integration-tests
        files: coverage-integration.out
        fail_ci_if_error: false
