name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Download dependencies
      run: mage tidy

    - name: Run tests with coverage
      run: mage coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        use_oidc: true
        flags: unit-tests
        files: coverage.out
        fail_ci_if_error: false
